### ISSUE TITLE
When duplicating a whole line, the cursor moves after the new line character

### ISSUE THREAD

**Issue by louije** [hutattedonmyarm/Duplicate#1]
Thanks a lot for this extension!

### The issue I have:

When hitting ⌘⇧D with nothing selected, the whole line is duplicated, new line character included. This moves the cursor to the beginning of the next line. This means that mashing ⌘⇧D multiple times does not copy the original line multiple times, but each time duplicates the next line.

The native "Copy Lines Down" feature does not behave like that (but it does not duplicate inner ranges like this extension does).

### What behavior would be expected:

When duplicating a whole line (like, when the selection's length is 0), the cursor should appear at the same position it had in the original line. That's how Sublime Text handles it.

**Comment by hutattedonmyarm** [comment]
Thanks, I had that initially and it drowned during some refactoring. Fixed in 1.0.2!
